<?php
require_once __DIR__ . '/../config.php';

$db = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if ($db->connect_error) {
    die("❌ DB connection failed: " . $db->connect_error . "\n");
}
$db->set_charset('utf8mb4');

// ── STEP 1: Pick random strategy ─────────────────────────────────────────

$aiMoneyStrategies = [

    [
        'type'   => 'ai_passive_income',
        'prompt' => 'You are a sharp digital entrepreneur writing for DEVELOP IT\'s blog.
Write a practical, slightly provocative article about generating PASSIVE INCOME using Claude AI.
Pick ONE specific angle:
"Comment j\'utilise Claude pour générer 3000 DH/mois en dormant (guide honnête)",
"5 business modèles passifs que vous pouvez lancer avec Claude en un weekend",
"Comment transformer Claude en machine à écrire qui vous paie chaque mois",
"J\'ai créé 12 sources de revenus passifs avec l\'IA — voici lesquelles marchent vraiment",
"Le guide que les gourous du business ne veulent pas que vous lisiez : revenus passifs IA",
"Comment des Marocains utilisent Claude pour vendre du contenu à des clients européens".
Include SPECIFIC tactics: exact prompts to use, platforms to sell on, realistic revenue ranges.
Be honest about what works and what is overhyped.
Add one unexpected income stream nobody talks about.
Make it feel like insider knowledge being shared for the first time.',
    ],

    [
        'type'   => 'ai_cash_machine',
        'prompt' => 'You are a digital business strategist writing for DEVELOP IT.
Write an actionable article about turning Claude AI into a revenue-generating machine.
Pick ONE specific angle:
"Comment vendre des services IA à 500€/client sans être développeur",
"Le business de revente IA : comment des freelances marocains facturent 10x plus avec Claude",
"Créer une agence IA solo avec Claude : de 0 à 50 000 DH/mois",
"Les 7 services IA que les PME paient cher et que vous pouvez livrer avec Claude",
"Comment j\'ai remplacé une équipe de 5 personnes avec Claude (et gardé le budget)",
"Vendre du contenu IA en arabe et en français : le marché inexploité du Maghreb".
Include: exact service packages with prices, how to find clients, scripts for selling.
Add a "dirty secret" section revealing what most people get wrong.
Include one case study with fake but realistic numbers.',
    ],

    [
        'type'   => 'ai_marketing_agency',
        'prompt' => 'You are a growth hacker writing for DEVELOP IT.
Write a tactical article about using Claude as a full creative marketing agency.
Pick ONE angle:
"Comment utiliser Claude comme votre agence marketing complète (et licencier votre freelance)",
"Le système en 5 étapes pour produire 30 jours de contenu marketing en 2 heures avec Claude",
"Comment des entrepreneurs marocains utilisent Claude pour dominer leurs concurrents sur LinkedIn",
"Créer une stratégie marketing complète avec Claude : le guide pas à pas",
"Les prompts secrets pour transformer Claude en copywriter qui convertit vraiment",
"Comment j\'utilise Claude pour gérer 8 comptes clients en solo sans perdre la tête".
Include REAL prompts (show the actual prompt text the reader can copy-paste).
Include a content calendar template generated by Claude.
Add a "prompt that changed everything" moment.',
    ],

    [
        'type'   => 'ai_freelance_empire',
        'prompt' => 'You are a successful AI freelancer writing for DEVELOP IT.
Write an inspiring but practical article about building a freelance empire with Claude.
Pick ONE angle:
"De développeur à 15 000 DH/mois : comment Claude a transformé ma carrière freelance",
"Les 5 niches freelance où Claude vous rend 10x plus productif (et comment les monétiser)",
"Comment facturer 500€ pour un service que Claude fait en 20 minutes",
"Le manuel du freelance augmenté : travailler moins, gagner plus avec l\'IA",
"Fiverr + Claude = machine à cash : le guide complet pour le marché international",
"Comment vendre des services d\'automatisation IA à des PME marocaines qui ne savent pas ce que c\'est".
Include: pricing strategies, how to package AI services, how to handle clients.
Add a "what I wish I knew" section.
Include one counter-intuitive tip that sounds wrong but works.',
    ],

    [
        'type'   => 'ai_content_empire',
        'prompt' => 'You are a content entrepreneur writing for DEVELOP IT.
Write a practical guide about building a content empire using Claude.
Pick ONE angle:
"Comment créer un blog qui génère des revenus publicitaires avec Claude en 90 jours",
"Le système pour gérer 5 comptes Instagram en arabe et français avec Claude seul",
"Comment j\'ai lancé une newsletter payante avec Claude comme co-auteur (800 abonnés en 3 mois)",
"Créer et vendre des ebooks avec Claude : de l\'idée à 1000 DH en 72 heures",
"Le business de la formation en ligne propulsé par Claude : créer un cours complet en un weekend",
"Comment utiliser Claude pour dominer le SEO en darija et en français".
Include: exact workflow, time investment vs return, platforms to use.
Show a real example with fake but specific numbers.
Add the one prompt that does 80% of the work.',
    ],

    [
        'type'   => 'ai_automation_money',
        'prompt' => 'You are an automation expert writing for DEVELOP IT.
Write a mind-opening article about making money by automating things with Claude.
Pick ONE angle:
"Comment vendre des automations Claude à des PME pour 5000 DH/mois sans coder",
"Les 6 tâches d\'entreprise que Claude automatise et pour lesquelles les gens paient cher",
"Créer des agents IA personnalisés et les vendre : le nouveau business des intégrateurs IA",
"Comment j\'ai automatisé mon service client avec Claude et économisé 8h/semaine",
"Le business des templates Claude : créer une fois, vendre à l\'infini",
"Construire un SaaS micro avec Claude comme cerveau : de l\'idée au premier client payant".
Include: what automation to build first, how to price it, how to sell it.
Add a "surprising automation" nobody thinks of but everyone needs.
Include one copy-paste prompt readers can use immediately.',
    ],

    [
        'type'   => 'ai_tips_secrets',
        'prompt' => 'You are an AI power user sharing insider knowledge for DEVELOP IT.
Write a "secrets revealed" style article about using Claude effectively.
Pick ONE angle:
"Les 10 prompts Claude que les experts cachent jalousement (le n°7 est stupidement simple)",
"Comment utiliser Claude comme un consultant à 500€/h pour 20$/mois",
"Les techniques avancées de prompt engineering que seuls 1% des utilisateurs connaissent",
"Comment Claude peut remplacer 8 abonnements SaaS que vous payez chaque mois",
"Les erreurs que 95% des utilisateurs de Claude font (et comment les éviter)",
"Transformer Claude en expert de n\'importe quel domaine en 3 prompts".
Include: actual prompt examples readers can copy, before/after comparisons.
Use a "forbidden knowledge" tone — like sharing something you shouldn\'t.
Add one genuinely surprising capability that most people don\'t know about.
Make readers feel they just discovered something valuable.',
    ],
];

$otherStrategies = [

    [
        'type'   => 'humor',
        'prompt' => 'You are a genuinely funny tech writer for DEVELOP IT. Write a HILARIOUS blog post in French.
Pick ONE angle:
"10 signes que votre service IT est coincé en 2005 (le n°7 va vous faire pleurer)",
"Le guide de survie du développeur marocain : gérer un client qui veut Facebook + Airbnb + Amazon pour 5000 DH",
"Les 7 étapes du deuil quand votre ERP plante le jour de paie",
"Les vraies descriptions de postes dans les boîtes tech marocaines",
"Pourquoi votre patron pense encore qu\'Excel peut tout faire en 2025",
"Ce que votre style de code dit sur votre personnalité (et ce n\'est pas flatteur)".
Use real humor: clever wordplay, absurd situations, recognizable Moroccan business culture.
Include emojis strategically. Make section titles funny. End with a punchline.
This should make people laugh out loud AND share it with colleagues.',
    ],

    [
        'type'   => 'roast',
        'prompt' => 'You are a witty tech writer doing a FRIENDLY ROAST for DEVELOP IT.
Pick ONE target to roast with affection:
"Roast des startups marocaines : on vous aime mais on doit parler",
"Roast des clients qui veulent tout pour rien : témoignage d\'un développeur en larmes",
"Roast des boîtes qui refusent la digitalisation en 2025",
"Roast du syndrome \'mon neveu peut faire ça\' chez les décideurs",
"Roast des réunions Zoom inutiles : 45 minutes de votre vie perdues à jamais",
"Roast des développeurs PHP : les héros incompris et sous-payés du web".
Be funny but never mean-spirited. Include 3 genuinely funny jokes.
End with something heartwarming that redeems everyone.',
    ],

    [
        'type'   => 'myth_busting',
        'prompt' => 'You are a no-nonsense tech expert writing for DEVELOP IT.
Write a myth-busting article. Pick ONE:
"5 mythes sur l\'IA que votre patron croit encore (et qui lui coûtent de l\'argent)",
"La vérité sur le no-code que personne ne vous dit",
"7 mensonges que les agences digitales vous vendent (oui, on fait partie du problème)",
"Non, l\'IA ne va pas vous remplacer — mais voici ce qui va vraiment changer",
"Les vraies raisons pourquoi votre site ne génère pas de leads (ce n\'est pas le design)".
Structure: myth → brutal reality → what to do instead.
Add one self-aware joke about DEVELOP IT being a digital agency that sells these services.
Make readers feel smart for reading this.',
    ],

    [
        'type'   => 'opinion',
        'prompt' => 'You are a bold, slightly provocative tech commentator for DEVELOP IT.
Write a CONTROVERSIAL opinion article. Pick ONE:
"ChatGPT killed junior developers (or did it?) — mon opinion honnête",
"Pourquoi la plupart des startups IA vont échouer en 2025 (et le méritent)",
"La vraie raison pour laquelle les boîtes marocaines résistent à la digitalisation",
"Votre IT guy vous ment sur pourquoi vous n\'avez pas besoin d\'un ERP",
"Stop using Excel for everything — une intervention nécessaire".
Be direct, witty, backed by data. Use a clickbait headline that makes people say "wait, what?".
Include at least one sharp joke and one stat that surprises.',
    ],

    [
        'type'   => 'casestudy',
        'prompt' => 'You are a business consultant writing for DEVELOP IT.
Write a compelling case study. Pick ONE:
"Comment une PME de Casablanca a réduit ses coûts de 40% avec l\'IA",
"On a construit un chatbot WhatsApp en 48h — voici ce qui s\'est passé (honnêtement)",
"D\'Excel au chaos au ERP en 30 jours — le vrai bilan sans bullshit",
"Comment l\'IA a aidé un exportateur marocain à décrocher des clients européens".
Include fake but realistic numbers. Add a "what went wrong" section.
Include one funny or self-deprecating moment. Make it feel like a real story.',
    ],
];

// 60% AI money topics, 40% other
$rand = rand(1, 10);
if ($rand <= 6) {
    $strategy = $aiMoneyStrategies[array_rand($aiMoneyStrategies)];
} else {
    $strategy = $otherStrategies[array_rand($otherStrategies)];
}

echo "📝 Strategy: {$strategy['type']}\n";

// ── STEP 2: Build the full prompt ─────────────────────────────────────────

$baseInstructions = 'IMPORTANT INSTRUCTIONS:
- Language: French primarily, with English tech terms kept in English (Claude, AI, ERP, SaaS, prompt)
- Minimum 800 words of actual content
- Content format: clean HTML only (<h2>, <h3>, <p>, <ul>, <ol>, <blockquote>, <strong>, <em>, <code>)
- NO markdown, NO backticks anywhere in JSON values
- Escape all double quotes inside JSON string values with \"

TITLE RULES — make it impossible NOT to click:
- Use curiosity gaps: "ce que personne ne dit", "la vérité sur", "le secret de"
- Use numbers: "7 façons", "5 erreurs", "3 prompts"
- Use parenthetical hooks: "(le n°4 va vous surprendre)", "(et comment en profiter)"
- Use money/results: "3000 DH/mois", "500€/client", "10x plus productif"
- NEVER write generic titles — every title must make someone stop scrolling

CONTENT RULES:
- Include at least ONE copy-paste prompt example if the article is about Claude/AI
- Include realistic numbers (revenue, time saved, cost) even if fictional
- Add one "unexpected tip" or "dirty secret" section that delivers genuine surprise value
- For money/income articles: be specific about HOW (platforms, pricing, scripts)
- Add personality — write like a smart friend sharing insider knowledge, not a corporate blog
- Include minimum 1 joke or witty observation even in serious articles

LINKEDIN POST RULES by type:
- ai_passive_income: "Vous dormez pendant que votre IA travaille ? Voici comment 👇"
- ai_cash_machine: Start with a specific income number to stop the scroll
- ai_marketing_agency: Start with "Licenciez votre agence marketing. Je vais vous expliquer."
- ai_freelance_empire: Start with a before/after: "Avant Claude : X DH/mois. Après : Y DH/mois"
- ai_content_empire: Start with a surprising content production stat
- ai_automation_money: Start with "Les PME paient 5000 DH/mois pour ça. Claude le fait pour 20$."
- ai_tips_secrets: Start with "Ce prompt m\'a fait gagner X heures cette semaine 🤫"
- humor: Start with the funniest line
- roast: Start with "On vous aime, mais on doit parler de..."
- myth_busting: Start with "Arrêtons de nous mentir :"
- opinion: Start with a controversial one-liner
- casestudy: Start with the result number

ENGAGEMENT HOOK at end of linkedin_post:
- Ask a question that provokes responses: "Vous utilisez déjà cette technique ?"
- Or make a bold statement: "Ceux qui ne font pas ça en 2025 vont souffrir."
- Or create FOMO: "Le prochain article explique comment doubler ça."

FACEBOOK POST RULES:
- Max 700 chars — Facebook rewards concise, conversation-starting posts
- Tone is more casual and warm than LinkedIn (write like a friend, not a professional)
- Use 2-3 emojis max, placed naturally (not clustered at end)
- Use 2-3 relevant hashtags max, appended at the very end
- MUST end with a direct question to the reader to encourage comments
- Then the URL on its own line: {URL}
- Avoid corporate speak — short sentences, conversational French
- Examples by type:
  - ai_passive_income: "Et si votre téléphone travaillait pendant que vous dormez ? 😴"
  - ai_cash_machine: "Quelqu\'un dans notre réseau a fait X DH ce mois avec juste Claude..."
  - humor: Lead with the punchline or the most absurd situation
  - myth_busting: "On va briser un mythe aujourd\'hui :"
  - opinion: A bold statement that makes people want to agree OR disagree
  - casestudy: Lead with the result, then tease the method

Return ONLY valid JSON (no markdown fences, no extra text) with these exact fields:
{
  "title": "Clickworthy title with hook and specifics (60-70 chars)",
  "slug": "url-friendly-slug-no-accents-no-special-chars",
  "excerpt": "Intriguing 160-char teaser that creates curiosity and promises value",
  "meta_title": "SEO-optimized title",
  "meta_description": "155-160 char meta description with hook and keywords",
  "meta_keywords": "6-8 comma-separated relevant keywords",
  "cover_keywords": "3-4 specific English words for Unsplash image search",
  "content": "Full article HTML 800+ words — specific, actionable, with personality and humor",
  "linkedin_post": "LinkedIn post max 1200 chars, line breaks after each idea, 3-5 emojis, 4-5 hashtags, engagement hook at end, must end with: Lire l article complet 👉 {URL}",
  "facebook_post": "Facebook post max 700 chars, casual tone, 2-3 emojis, 2-3 hashtags at end, must end with a question then URL on new line: {URL}"
}';

$fullPrompt = $strategy['prompt'] . "\n\n" . $baseInstructions;

// ── STEP 3: Generate with Claude ──────────────────────────────────────────

echo "🤖 Generating content...\n";
$response = callClaude($fullPrompt);
if (!$response) { die("❌ Claude API failed\n"); }

// Clean JSON if Claude wrapped it in backticks
$response = preg_replace('/^```json\s*/i', '', trim($response));
$response = preg_replace('/```\s*$/', '', $response);

$data = json_decode($response, true);
if (!$data || empty($data['title'])) {
    echo "Raw response:\n$response\n";
    die("❌ Invalid JSON\n");
}

echo "✅ Title: {$data['title']}\n";
echo "📋 Type: {$strategy['type']}\n";

// ── STEP 4: Get image from Unsplash ───────────────────────────────────────

echo "🖼️  Fetching image for: {$data['cover_keywords']}\n";
$imgUrl = getUnsplashImage($data['cover_keywords'], $strategy['type']);
if (!$imgUrl) {
    echo "⚠️  Image fetch failed, using fallback\n";
    $imgUrl = 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80';
}
echo "🖼️  Image: $imgUrl\n";

// ── STEP 5: Save to DB ────────────────────────────────────────────────────

$slug = generateUniqueSlug($data['slug'], $db);

// FIX 2: Define $blogUrl AFTER $slug is generated
$blogUrl = SITE_URL . "/blog/post.php?slug=" . urlencode($slug);
echo "🔗 URL: $blogUrl\n";

$fields = [
    'title'            => $data['title'],
    'slug'             => $slug,
    'excerpt'          => $data['excerpt'],
    'content'          => $data['content'],
    'cover_image'      => $imgUrl,
    'meta_title'       => $data['meta_title'] ?: $data['title'],
    'meta_description' => $data['meta_description'] ?: $data['excerpt'],
    'meta_keywords'    => $data['meta_keywords'] ?? '',
    'author'           => 'DEVELOP IT',
    'status'           => 'published',
];

$cols = implode(', ', array_keys($fields));
$vals = implode(', ', array_map(fn($v) => "'" . $db->real_escape_string($v) . "'", $fields));
$sql  = "INSERT INTO blogs ($cols) VALUES ($vals)";

$result = $db->query($sql);
if (!$result) {
    echo "❌ DB Error: " . $db->error . "\n";
    echo "SQL (first 300): " . substr($sql, 0, 300) . "...\n";
    die();
}

$blogId = $db->insert_id;
echo "💾 Saved to DB (ID: $blogId)\n";

// ── STEP 6: Post to LinkedIn ──────────────────────────────────────────────

echo "📤 Posting to LinkedIn...\n";

$liText = str_replace('{URL}', $blogUrl, $data['linkedin_post']);
$ok     = postToLinkedIn($liText, $blogUrl, $data['title'], $data['excerpt'], $imgUrl);
echo $ok ? "✅ LinkedIn published!\n" : "⚠️  LinkedIn failed (token not configured?)\n";

// ── STEP 7: Post to Facebook ──────────────────────────────────────────

echo "📤 Posting to Facebook...\n";

if (!empty($data['facebook_post'])) {
    $fbText = str_replace('{URL}', $blogUrl, $data['facebook_post']);
    $ok     = postToFacebook($fbText, $blogUrl, $data['title'], $imgUrl);
    echo $ok ? "✅ Facebook published!\n" : "⚠️  Facebook failed (token not configured?)\n";
} else {
    echo "⚠️  No facebook_post in AI response, skipping Facebook\n";
}

echo "\n🎉 Done! → $blogUrl\n";

// ── HELPERS ───────────────────────────────────────────────────────────────

function callClaude(string $prompt): ?string {
    $payload = json_encode([
        'model'      => 'claude-sonnet-4-20250514',
        'max_tokens' => 4000,
        'messages'   => [['role' => 'user', 'content' => $prompt]]
    ]);
    $ch = curl_init('https://api.anthropic.com/v1/messages');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $payload,
        CURLOPT_HTTPHEADER     => [
            'Content-Type: application/json',
            'x-api-key: ' . ANTHROPIC_API_KEY,
            'anthropic-version: 2023-06-01'
        ],
        CURLOPT_TIMEOUT        => 60,
        CURLOPT_SSL_VERIFYPEER => false,
    ]);
    $res  = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($code !== 200) { echo "Claude error ($code): $res\n"; return null; }
    $body = json_decode($res, true);
    return $body['content'][0]['text'] ?? null;
}

function getUnsplashImage(string $keywords, string $type): string {
    $typeOverrides = [
        'humor'      => ['team laughing office', 'funny developer coffee', 'office humor meeting', 'creative team fun'],
        'opinion'    => ['bold statement wall', 'thinking businessman', 'debate discussion team', 'idea lightbulb dark'],
        'news'       => ['breaking news screen', 'technology announcement', 'digital news media', 'tech conference stage'],
        'casestudy'  => ['business success chart', 'team celebrating results', 'data growth dashboard', 'moroccan business office'],
        'listicle'   => ['checklist productivity', 'tools workspace desk', 'organized planning board', 'business tools flat lay'],
        'educational'=> null,
    ];

    if ($type === 'humor' && isset($typeOverrides['humor'])) {
        $keywords = $typeOverrides['humor'][array_rand($typeOverrides['humor'])];
    } elseif (isset($typeOverrides[$type]) && $typeOverrides[$type] !== null && rand(0, 1)) {
        $arr      = $typeOverrides[$type];
        $keywords = $arr[array_rand($arr)];
    }

    $query = urlencode($keywords);
    $url   = "https://api.unsplash.com/photos/random?query={$query}&orientation=landscape&client_id=" . UNSPLASH_KEY;

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER     => ['Accept-Version: v1'],
        CURLOPT_TIMEOUT        => 10,
        CURLOPT_SSL_VERIFYPEER => false,
    ]);
    $res = json_decode(curl_exec($ch), true);
    curl_close($ch);

    if (!empty($res['urls']['regular'])) {
        return $res['urls']['regular'];
    }

    // Typed fallbacks
    $fallbacks = [
        'humor'      => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&q=80',
        'opinion'    => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=80',
        'news'       => 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80',
        'casestudy'  => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
        'listicle'   => 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=1200&q=80',
        'educational'=> 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80',
    ];
    return $fallbacks[$type] ?? $fallbacks['educational'];
}

function postToLinkedIn(string $text, string $url, string $title, string $desc, string $imgUrl): bool {

    // ── STEP 1: Register image upload ─────────────────────────────────────
    $registerPayload = json_encode([
        'registerUploadRequest' => [
            'owner'                  => LINKEDIN_PERSON_URN,
            'recipes'                => ['urn:li:digitalmediaRecipe:feedshare-image'],
            'serviceRelationships'   => [[
                'identifier'       => 'urn:li:userGeneratedContent',
                'relationshipType' => 'OWNER'
            ]],
            'supportedUploadMechanism' => ['SYNCHRONOUS_UPLOAD']
        ]
    ]);

    $ch = curl_init('https://api.linkedin.com/v2/assets?action=registerUpload');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $registerPayload,
        CURLOPT_HTTPHEADER     => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . LINKEDIN_TOKEN,
            'X-Restli-Protocol-Version: 2.0.0'
        ],
        CURLOPT_SSL_VERIFYPEER => false
    ]);
    $registerRes  = json_decode(curl_exec($ch), true);
    $registerCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($registerCode !== 200 || empty($registerRes['value']['uploadMechanism'])) {
        echo "❌ LinkedIn register upload failed ($registerCode): " . json_encode($registerRes) . "\n";
        return postToLinkedInTextOnly($text, $url, $title, $desc);
    }

    $uploadUrl = $registerRes['value']['uploadMechanism']
                    ['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest']
                    ['uploadUrl'];
    $assetUrn  = $registerRes['value']['asset'];

    echo "📤 Upload URL obtained, uploading image...\n";

    // ── STEP 2: Download image to temp file ───────────────────────────────
    $tmpFile = tempnam(sys_get_temp_dir(), 'li_img_') . '.jpg';
    $imgData = file_get_contents($imgUrl);

    if (!$imgData) {
        echo "⚠️  Could not download image, falling back to text post\n";
        return postToLinkedInTextOnly($text, $url, $title, $desc);
    }
    file_put_contents($tmpFile, $imgData);

    // ── STEP 3: Upload image to LinkedIn ──────────────────────────────────
    $ch = curl_init($uploadUrl);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_PUT            => true,
        CURLOPT_INFILE         => fopen($tmpFile, 'r'),
        CURLOPT_INFILESIZE     => filesize($tmpFile),
        CURLOPT_HTTPHEADER     => [
            'Authorization: Bearer ' . LINKEDIN_TOKEN,
            'Content-Type: image/jpeg'
        ],
        CURLOPT_SSL_VERIFYPEER => false
    ]);
    $uploadRes  = curl_exec($ch);
    $uploadCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    unlink($tmpFile);

    if ($uploadCode !== 201 && $uploadCode !== 200) {
        echo "⚠️  Image upload failed ($uploadCode), falling back to text post\n";
        return postToLinkedInTextOnly($text, $url, $title, $desc);
    }

    echo "✅ Image uploaded (asset: $assetUrn)\n";

    // ── STEP 4: Create post with image ────────────────────────────────────
    $postPayload = json_encode([
        'author'          => LINKEDIN_PERSON_URN,
        'lifecycleState'  => 'PUBLISHED',
        'specificContent' => [
            'com.linkedin.ugc.ShareContent' => [
                'shareCommentary'    => ['text' => $text],
                'shareMediaCategory' => 'IMAGE',
                'media'              => [[
                    'status'      => 'READY',
                    'media'       => $assetUrn,
                    'title'       => ['text' => mb_substr($title, 0, 200)],
                    'description' => ['text' => mb_substr($desc, 0, 256)]
                ]]
            ]
        ],
        'visibility' => ['com.linkedin.ugc.MemberNetworkVisibility' => 'PUBLIC']
    ]);

    $ch = curl_init('https://api.linkedin.com/v2/ugcPosts');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $postPayload,
        CURLOPT_HTTPHEADER     => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . LINKEDIN_TOKEN,
            'X-Restli-Protocol-Version: 2.0.0'
        ],
        CURLOPT_SSL_VERIFYPEER => false
    ]);
    $postRes  = curl_exec($ch);
    $postCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    echo "LinkedIn post ($postCode): $postRes\n";
    return $postCode === 201;
}

// ── Fallback: post without image ──────────────────────────────────────────
function postToLinkedInTextOnly(string $text, string $url, string $title, string $desc): bool {
    $payload = json_encode([
        'author'          => LINKEDIN_PERSON_URN,
        'lifecycleState'  => 'PUBLISHED',
        'specificContent' => [
            'com.linkedin.ugc.ShareContent' => [
                'shareCommentary'    => ['text' => $text],
                'shareMediaCategory' => 'ARTICLE',
                'media'              => [[
                    'status'      => 'READY',
                    'originalUrl' => $url,
                    'title'       => ['text' => mb_substr($title, 0, 200)],
                    'description' => ['text' => mb_substr($desc, 0, 256)]
                ]]
            ]
        ],
        'visibility' => ['com.linkedin.ugc.MemberNetworkVisibility' => 'PUBLIC']
    ]);

    $ch = curl_init('https://api.linkedin.com/v2/ugcPosts');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $payload,
        CURLOPT_HTTPHEADER     => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . LINKEDIN_TOKEN,
            'X-Restli-Protocol-Version: 2.0.0'
        ],
        CURLOPT_SSL_VERIFYPEER => false
    ]);
    $res  = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    echo "LinkedIn fallback ($code): $res\n";
    return $code === 201;
}

function generateUniqueSlug(string $base, mysqli $db): string {
    $slug = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $base);
    $slug = strtolower($slug);
    $slug = preg_replace('/[^a-z0-9]+/', '-', $slug);
    $slug = trim($slug, '-');
    $slug = preg_replace('/-+/', '-', $slug);

    $orig = $slug;
    $i    = 1;
    while ($db->query("SELECT id FROM blogs WHERE slug='" . $db->real_escape_string($slug) . "'")->num_rows > 0) {
        $slug = $orig . '-' . $i++;
    }
    return $slug;
}

// ── Facebook helpers ──────────────────────────────────────────────────────────

/**
 * Post to a Facebook Page using the Graph API v19.0.
 * Tries a photo post first (richer engagement), falls back to a link post.
 *
 * Requires FACEBOOK_PAGE_ID and FACEBOOK_PAGE_ACCESS_TOKEN in .env.
 * Obtain a long-lived page access token via /blog/facebook-callback.php.
 */
function postToFacebook(string $text, string $url, string $title, string $imgUrl): bool {
    if (!FACEBOOK_PAGE_ID || !FACEBOOK_PAGE_ACCESS_TOKEN) {
        echo "⚠️  Facebook credentials not configured (FACEBOOK_PAGE_ID / FACEBOOK_PAGE_ACCESS_TOKEN)\n";
        return false;
    }

    // ── Attempt 1: photo post with caption (displays image inline, great for reach) ──
    $ch = curl_init('https://graph.facebook.com/v19.0/' . FACEBOOK_PAGE_ID . '/photos');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => [
            'url'          => $imgUrl,
            'caption'      => $text,
            'access_token' => FACEBOOK_PAGE_ACCESS_TOKEN,
        ],
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT        => 30,
    ]);
    $res  = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    echo "Facebook photo post ($code): $res\n";

    if ($code === 200) {
        return true;
    }

    // ── Attempt 2: feed post with link preview ────────────────────────────────
    echo "⚠️  Photo post failed, falling back to feed post\n";
    return postToFacebookTextOnly($text, $url);
}

/**
 * Post a plain message + link to a Facebook Page (no image).
 * Facebook will generate a link preview card automatically.
 */
function postToFacebookTextOnly(string $text, string $url): bool {
    if (!FACEBOOK_PAGE_ID || !FACEBOOK_PAGE_ACCESS_TOKEN) {
        return false;
    }

    $ch = curl_init('https://graph.facebook.com/v19.0/' . FACEBOOK_PAGE_ID . '/feed');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => [
            'message'      => $text,
            'link'         => $url,
            'access_token' => FACEBOOK_PAGE_ACCESS_TOKEN,
        ],
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT        => 30,
    ]);
    $res  = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    echo "Facebook feed post ($code): $res\n";
    return $code === 200;
}


